# CloudNativePG Cluster Settings
cnpg:
  namespace: enginevector-cnpg-cluster
  primaryServiceName: enginevector-storage-postgresql-cluster-rw  # Update this if necessary
  appUserSecret:
    name: enginevector-user-secret
    username: enginevector
    password: enginevectorpassword