apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cnpg.schemaConfigMap.name }}
  namespace: {{ .Values.cnpg.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.cnpg.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
data:
  schema.sql: |-
    {{ (.Files.Get "enginevector-lottery-schema.sql" | nindent 8) }}
